[project]
name = "xhs-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "curl-cffi>=0.10.0",
    "mcp[cli]>=1.6.0",
    "pyexecjs>=1.5.1",
    "requests>=2.32.3",
    "selenium>=4.34.2",
    "loguru>=0.7.2"
]

[tool.setuptools.packages.find]
include = ["api*"]
exclude = ["logs*"]
